# Generated by Django 5.2.5 on 2026-03-28 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=500)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("chunks_count", models.IntegerField(default=0)),
                ("entities_count", models.IntegerField(default=0)),
                ("relationships_count", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Processing time in seconds", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["-uploaded_at", "status"],
                        name="rag_documen_uploade_b210b0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GraphEntity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=500)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("PERSON", "Person"),
                            ("ORGANIZATION", "Organization"),
                            ("LOCATION", "Location"),
                            ("CONCEPT", "Concept"),
                            ("TECHNOLOGY", "Technology"),
                            ("EVENT", "Event"),
                            ("PRODUCT", "Product"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("properties", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Graph Entities",
                "indexes": [
                    models.Index(
                        fields=["name", "entity_type"],
                        name="rag_graphen_name_a32a63_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.TextField()),
                ("answer", models.TextField(blank=True, null=True)),
                (
                    "strategy_used",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("agentic", "Agentic"),
                            ("multi_agent", "Multi-Agent"),
                            ("auto", "Auto"),
                        ],
                        db_index=True,
                        default="auto",
                        max_length=20,
                    ),
                ),
                (
                    "query_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("question", "Question"),
                            ("search", "Search"),
                            ("analysis", "Analysis"),
                            ("summarization", "Summarization"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("retrieved_chunks_count", models.IntegerField(default=0)),
                ("agent_steps_count", models.IntegerField(default=0)),
                ("agents_used", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queries",
                        to="rag.document",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_type", models.CharField(db_index=True, max_length=100)),
                ("agent_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("steps_count", models.IntegerField(default=0)),
                ("tools_used", models.JSONField(blank=True, default=list)),
                ("output", models.TextField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_executions",
                        to="rag.query",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="RLEpisodeSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("total_steps", models.IntegerField(default=0)),
                ("total_reward", models.FloatField(default=0.0)),
                ("final_confidence", models.FloatField(blank=True, null=True)),
                ("epsilon_at_end", models.FloatField(blank=True, null=True)),
                ("actions_taken", models.JSONField(default=list)),
                ("used_internet", models.BooleanField(default=False)),
                ("user_feedback", models.CharField(default="none", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="rag_rlepiso_created_e2bcc4_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RLExperienceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_id", models.CharField(db_index=True, max_length=100)),
                (
                    "rl_state",
                    models.JSONField(
                        help_text="[conf_bucket, retr_bucket, comp_bucket, has_internet]"
                    ),
                ),
                ("action_idx", models.IntegerField()),
                (
                    "action_name",
                    models.CharField(
                        choices=[
                            ("RETRIEVE_MORE", "Retrieve More"),
                            ("RE_RANK", "Re-Rank"),
                            ("ANSWER_NOW", "Answer Now"),
                            ("ASK_CLARIFICATION", "Ask Clarification"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("reward", models.FloatField()),
                ("next_rl_state", models.JSONField()),
                ("done", models.BooleanField(db_index=True, default=False)),
                (
                    "user_feedback",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("none", "None"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["query_id", "created_at"],
                        name="rag_rlexper_query_i_9c79e5_idx",
                    ),
                    models.Index(
                        fields=["action_name", "-created_at"],
                        name="rag_rlexper_action__1001d4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("message_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["-last_activity", "is_active"],
                        name="rag_session_last_ac_037d4c_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="query",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queries",
                to="rag.session",
            ),
        ),
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("memory_type", models.CharField(db_index=True, max_length=50)),
                ("content", models.TextField()),
                ("importance_score", models.FloatField(default=0.5)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("access_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="rag.session",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agent Memories",
                "ordering": ["-last_accessed"],
            },
        ),
        migrations.CreateModel(
            name="ToolExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("tool_input", models.JSONField(default=dict)),
                ("tool_output", models.JSONField(blank=True, null=True)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "agent_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_executions",
                        to="rag.agentexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("chunk_index", models.IntegerField(db_index=True)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="rag.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="rag_documen_documen_637082_idx",
                    )
                ],
                "unique_together": {("document", "chunk_index")},
            },
        ),
        migrations.CreateModel(
            name="GraphRelationship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relation_type", models.CharField(db_index=True, max_length=100)),
                ("weight", models.FloatField(default=1.0)),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="rag.graphentity",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="rag.graphentity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "relation_type"],
                        name="rag_graphre_source__178c82_idx",
                    ),
                    models.Index(
                        fields=["target", "relation_type"],
                        name="rag_graphre_target__340a55_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["query", "-start_time"], name="rag_agentex_query_i_5861ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["agent_type", "-start_time"],
                name="rag_agentex_agent_t_baf67f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["-created_at", "strategy_used"],
                name="rag_query_created_691f45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["session", "-created_at"], name="rag_query_session_3884f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(
                fields=["session", "-last_accessed"],
                name="rag_agentme_session_374fd6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(
                fields=["memory_type", "-last_accessed"],
                name="rag_agentme_memory__87b68b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="toolexecution",
            index=models.Index(
                fields=["agent_execution", "created_at"],
                name="rag_toolexe_agent_e_2f4a8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="toolexecution",
            index=models.Index(
                fields=["tool_name", "-created_at"],
                name="rag_toolexe_tool_na_b46fdc_idx",
            ),
        ),
    ]
